### ISSUE TITLE
Feature: User can search for a city and be able to view hotels in the area

### ISSUE THREAD

**Issue by moamel-hashim** [moamel-hashim/travel-guide#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

user can search for a vacation in any area in the us 
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

the user will input a search on the home page once they press enter then they will be 
directed to another page that shows them all the top-rated hotels in the area.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Capture](https://user-images.githubusercontent.com/90476994/163293352-312f6dd7-cbe7-4833-a64a-2c924a420bda.PNG)
![Capture](https://user-images.githubusercontent.com/90476994/163293840-95641431-16ba-428c-9cc0-4535b017cc5f.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] update 'schema.sql' to include the table database that is been created in the DB database
- [x] Update `data.sql` to include the data in the schema file 

### ☁️ Server

- [x] Update `server/index.js` to fetch api request and retrieve data 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] creating  a component for the client to be able to view the home page
- [x] mount the fetched data from the API to the app
- [x] creating a component for the client to be able to view all the hotels in the area depending on their search results

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
