### ISSUE TITLE
Feature: User can view restaurants in the area 

### ISSUE THREAD

**Issue by moamel-hashim** [moamel-hashim/travel-guide#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can view all the top-rated restaurants in the area when they conduct a search 
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

when a user searches for a city on the home page they will be able to view all the restaurants
nearby 
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Capture](https://user-images.githubusercontent.com/90476994/163296722-f61cce66-2435-496e-903f-8bd4802a32a8.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [ ] Create a component to view all the restaurants in the area
- [ ] Create a component that listens for the get directions button so that when a user clicks on the button it gives them directions to the restaurant 

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
